# NOTE BOOK FOR PYTORCH TENSOR TYPE AND DEFINITION

In [2]:
import torch
### Common type and syntax of creating tensor

In [2]:
# Tensor support for multiple type go from a scalar -> vector -> matrix -> actual tensor it self
scalar = torch.tensor([[[1,2,3],
						[3,4,5],
						[5,6,7]]])
print(scalar.ndim)
print(scalar.shape)


3
torch.Size([1, 3, 3])


In [3]:
# create random tensor since neural network learn from this shiet
random_ten = torch.rand(3, 244, 244)
print(random_ten.shape, random_ten.ndim)

ones = torch.ones(3,4)
print(ones.dtype)


torch.Size([3, 244, 244]) 3
torch.float32


In [4]:

#use torch.arange() instead of torch.range()
print(torch.arange(start=1, end=100, step=30).cuda())

# creating tensors like 
ten_zeroes = torch.zeros_like(input = torch.arange(start=1, end=100, step=30))
print(ten_zeroes)


tensor([ 1, 31, 61, 91], device='cuda:0')
tensor([0, 0, 0, 0])


In [11]:
#Now for tensor datatype 
# Big 3 issues that you will frequently have when using this bad boyis 
# - Out of shape (mine persional normally encouter)
# - Not correct device 
# - Not right datatype
temp = torch.ones(size=(1,3),  dtype=torch.float32)
print(temp.type(torch.float16))
print(torch.tensor([3.0, 2.0, 1.0], dtype=torch.float64, device="cuda", requires_grad=False) - temp.cuda())

tensor([[1., 1., 1.]], dtype=torch.float16)
tensor([[2., 1., 0.]], device='cuda:0', dtype=torch.float64)


In [14]:
float_16_tensor = torch.tensor([3.0, 2.1, 1.1], dtype=torch.float32)
print(float_16_tensor)
int_32_tensor = torch.tensor([1,2,3], dtype=torch.int32)
print(int_32_tensor - float_16_tensor)

tensor([3.0000, 2.1000, 1.1000])
tensor([-2.0000, -0.1000,  1.9000])


## Getting information from tensor 

### 1. Tensors not right datatype - to do get datatype from a tensor, can use 'tensor.dtype'
### 2. Tensor not right shape - to get shape from a tensor, can use tensor.shape
### 3. Tensors not on the right device - to get device from a tensor, use tensor.device

In [3]:
some_tensor = torch.rand(size = (3,4), device= 0)
some_tensor
# print the datatype of tensor 
some_tensor.dtype
# print the shape of the tensor 
some_tensor.shape
# print device of the tensor
some_tensor.device

device(type='cuda', index=0)

### Manipulating Tensors common method 

Some common operations are: 
 - `"+"` Addition 
 - `"-"` Subtraction
 - `"*"` Multiplication (element-wise)
 - `"/"` Devision
 - `"@"` Matrix multiplication

In [16]:
# Maniplulate tensors:
tensor = torch.tensor([1,2,3])
print(tensor + 10)
print(tensor * 10)
print(tensor - 10)

# You can even try Pytorch built in function
# Note thta mul here is matrix mul not element wise 
print(torch.mul(tensor, 10))
print(torch.add(tensor, 10))

tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([11, 12, 13])


### Matrix mul

Two main ways of doing this mul: 
1. Element wise
2. Dot product

There are two main rules that performing dot product - matrix multiplication must satisfy: 
1. The **inner dimension** must match: 
* The columns of the left hand side must equal rows on the right hand side. 
* `(3, 2) @ (2, 3)` -> will work 
2. The resulting matrix will have the shape of **outer dimension**
* The resulting matrix will have the rows of the left hand side and columns of the right hand side.
* `(3, 2) @ (2, 3)` -> `(3, 3)`

To make the matrix multiplcation satisfy the rule, one common method is **transpose**

In [63]:
%%time
#  The transpose method
tensor = torch.tensor([[3,3],
					   [3,5],
					   [5,7]])
tensorB = torch.tensor([[3,3],
					   [3,5],
					   [5,7]])

# You can use alternate between the attribute T and torch built in method
print(torch.transpose(tensorB, 0, -1))
print(tensorB.T)

print(torch.matmul(tensor, torch.transpose(tensorB, 0, -1)).shape)
print(torch.matmul(tensor, tensorB.T))

# You can also see that the resulting matrix shape is 
print(f"Mulitiply two matrix with shape {tensor.shape} for {tensorB.T.shape} will give use {torch.matmul(tensor, tensorB.T).shape}")

tensor([[3, 3, 5],
        [3, 5, 7]])
tensor([[3, 3, 5],
        [3, 5, 7]])
torch.Size([3, 3])
tensor([[18, 24, 36],
        [24, 34, 50],
        [36, 50, 74]])
Mulitiply two matrix with shape torch.Size([3, 2]) for torch.Size([2, 3]) will give use torch.Size([3, 3])
CPU times: total: 0 ns
Wall time: 1 ms


## Some more common synxtax use as in nummpy: min, max, sum ... (aggregation)

In [82]:
# x = torch.arange(0, 100, 10)
x = torch.arange(start=0, end=100, step=10, dtype = torch.float32)

# You can once again use the built in Pytorch method
print(torch.min(x))
print(torch.max(x))
print(torch.mean(x.type(torch.float32)))
print(torch.sum(x))

# Or you can use the attribute way 
print(x.min())
print(x.max())
print(x.mean())
print(x.sum())

# you can print out the index where minimum value occur
print(torch.argmin(x))
print(torch.argmax(x))
print(torch.sort(x))

tensor(0.)
tensor(90.)
tensor(45.)
tensor(450.)
tensor(0.)
tensor(90.)
tensor(45.)
tensor(450.)
tensor(0)
tensor(9)
torch.return_types.sort(
values=tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.]),
indices=tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))


## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapre an input tensor into a defined shape 
* View - return a view of an input tensor of certain shape but keep the same memories as the original tensor
* Stacking - combine multiple tensors on top / side by side of each other
* Squeeze - remove all '1' dimensions
* Unsqueeze - add a '1' dimensions
* Permute - return a view of the input with dimension permuted (swapped) in certain way

In [99]:
# Let's create a tensor 
import torch
x = torch.arange(start = 1.0, end = 13.0, dtype=torch.float32)
print(x, x.shape)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]) torch.Size([12])


In [101]:
# Add an extra dimentsion 
x_reshaped = x.reshape(4, 3)
print(x_reshaped)
print(x_reshaped.shape)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
torch.Size([4, 3])


In [106]:
# Change the view
z = x.view(3, 4)
print(z)

# view = reshape but NOT create a copy, mean that view share the same mem as the original 
# Lets change all the row first number in to 5
z[:, 0] = 5

# You can see that changing z -> change x
print(x)

tensor([[ 5.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 5., 10., 11., 12.]])
tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  5., 10., 11., 12.])


In [115]:
# Stack tensors on top of each other
temp = torch.rand(3,4)
print(temp)
x_stacked = torch.stack([temp, temp, temp, temp], dim = 1)
print(x_stacked)

tensor([[0.4612, 0.2184, 0.8372, 0.8899],
        [0.2824, 0.5803, 0.0998, 0.9408],
        [0.7586, 0.2325, 0.4643, 0.3805]])
tensor([[[0.4612, 0.2184, 0.8372, 0.8899],
         [0.4612, 0.2184, 0.8372, 0.8899],
         [0.4612, 0.2184, 0.8372, 0.8899],
         [0.4612, 0.2184, 0.8372, 0.8899]],

        [[0.2824, 0.5803, 0.0998, 0.9408],
         [0.2824, 0.5803, 0.0998, 0.9408],
         [0.2824, 0.5803, 0.0998, 0.9408],
         [0.2824, 0.5803, 0.0998, 0.9408]],

        [[0.7586, 0.2325, 0.4643, 0.3805],
         [0.7586, 0.2325, 0.4643, 0.3805],
         [0.7586, 0.2325, 0.4643, 0.3805],
         [0.7586, 0.2325, 0.4643, 0.3805]]])


In [130]:
temp = torch.rand(1,2,1,3,1)
print(temp.squeeze())
squeeze_tensor = temp.squeeze()
print(squeeze_tensor.unsqueeze(2))

tensor([[0.1515, 0.8446, 0.8516],
        [0.3870, 0.1983, 0.2425]])
tensor([[[0.1515],
         [0.8446],
         [0.8516]],

        [[0.3870],
         [0.1983],
         [0.2425]]])
tensor([[[0.1515],
         [0.8446],
         [0.8516]],

        [[0.3870],
         [0.1983],
         [0.2425]]])


In [146]:
# permute - rearange the tensor element in a specify oder - also can under stand that you suffle up existing dimensions
temp = torch.rand(3,4,5)
print(temp)
print(torch.permute(temp, (2,0,1)))
print(torch.permute(temp, (2,1,0)))

tensor([[[0.9731, 0.7827, 0.1330, 0.7750, 0.0914],
         [0.3605, 0.6484, 0.3072, 0.7695, 0.6082],
         [0.2803, 0.5010, 0.1451, 0.7355, 0.0177],
         [0.8040, 0.3425, 0.2002, 0.3939, 0.9618]],

        [[0.7434, 0.4583, 0.2253, 0.4913, 0.1653],
         [0.1502, 0.1087, 0.6227, 0.1958, 0.1295],
         [0.2144, 0.6279, 0.7180, 0.2006, 0.4090],
         [0.7050, 0.9341, 0.4218, 0.9217, 0.3667]],

        [[0.7070, 0.1681, 0.7539, 0.8611, 0.6437],
         [0.2146, 0.0724, 0.0945, 0.3786, 0.7614],
         [0.1135, 0.1338, 0.7858, 0.0520, 0.3367],
         [0.6078, 0.0083, 0.6693, 0.1390, 0.4636]]])
tensor([[[0.9731, 0.3605, 0.2803, 0.8040],
         [0.7434, 0.1502, 0.2144, 0.7050],
         [0.7070, 0.2146, 0.1135, 0.6078]],

        [[0.7827, 0.6484, 0.5010, 0.3425],
         [0.4583, 0.1087, 0.6279, 0.9341],
         [0.1681, 0.0724, 0.1338, 0.0083]],

        [[0.1330, 0.3072, 0.1451, 0.2002],
         [0.2253, 0.6227, 0.7180, 0.4218],
         [0.7539, 0.0945, 0.7858, 

## Indexing (selecting element from a tensor)
Indexing in Pytorch share a large portion of simliarity to Numpy array

In [165]:
import torch
x = torch.arange(start= 1, end= 10, step=1).reshape(1, 3 , 3)
print(x)
print(x[0])
print(x[0][0])
print(x[0][1][1])


print(x[:, 0])
print(x[:, :, 1])
print(x[0, 0, :])

print(x[-1][-1][-1])
print(x[:, :, 2])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor(5)
tensor([[1, 2, 3]])
tensor([[2, 5, 8]])
tensor([1, 2, 3])
tensor(9)
tensor([[7, 8, 9]])


## PyTorch and Numpy
NumPy goes very well with PyTorch, PyTorch installation need NumPy, and interact very well with it. 
* Data in NumPy, have to convert into torch type to interact: `torch.from_numpy(ndarray)`
* Convert from PyTorch -> NumPy -> `torch.tensor.numpy()`

In [178]:
import torch
import numpy as np 

array = np.arange(1.0, 8.0)
another_array = np.array([1,2,3,4])
print(another_array)
tensor = torch.from_numpy(another_array + 1)

# Default data for numpy is float64 so torch reflect that data type
print(tensor)

tensor = torch.ones(3,4,4)
numpy_tensor = tensor.numpy()
# Default data of pytorch is 64, convert it to numpy will make numpy reflect that
print(numpy_tensor)

[1 2 3 4]
tensor([2, 3, 4, 5], dtype=torch.int32)
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


## Reproducibility (trying to make random out of random)

In short a neural network will learn like this: 
* Throw in a bunch random set of weight -> run the input through the network -> compare it with ground truth -> figure out how "wrong" is the output -> figure out how much to ajust the weight (back propagation) -> again .... 
* those run input through network, and ajust the weight bascially tensor operation

To reduce the randomnes in neural networks, PyTorch use random seed, to yeild the random. 

In [181]:
import torch

# Random in computer is not actually random, it is psuedo random, and if random start with a seed each time it will give us the same results
# each manual seed only work with one block of the next rand code
torch.manual_seed(42)
random_tensor_A = torch.rand(size=(3,3))
torch.manual_seed(42)
random_tensor_B = torch.rand(size=(3,3))
print(random_tensor_A)
print(random_tensor_B)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])


## Running pytorch's tensor computing on GPU

GPUs = parrallel - this is extremlly powerfull since tensor operation basically matrix multiplying 

### 1. Getting a GPU
1. Easiest - Use Google colab
2. Use your own GPU - instal CUDA, Cudnn, add it to path (Window)/source(Linux) and install the Torch with GPU version. 

In [189]:
!nvidia-smi

Sat Jan 25 19:13:51 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 561.09                 Driver Version: 561.09         CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060 Ti   WDDM  |   00000000:01:00.0  On |                  N/A |
| 33%   43C    P8             31W /  200W |    1416MiB /   8192MiB |     24%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [182]:
import torch
# Check for GPU accessable with pytorch 
print(torch.cuda.is_available())

True


In [185]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

cuda


In [183]:
# count the number of GPUs
print(torch.cuda.device_count())

1


### 2. Putting tensors (and model) on the GPU
The reason why we'd like to do this because the GPU is way more faster than CPU in computing tensor operations - the parallel ones.

In [190]:
# Create a tensor (default on CPU)
tensor = torch.tensor([1,2,3])
print(tensor.device)
tensor_on_gpu = tensor.to(device)
print(tensor_on_gpu.device)

cpu
cuda:0


In [188]:
### 3. Putting the tensor back to the CPU 

numpy_tensor = tensor_on_gpu.to("cpu").numpy()
print(numpy_tensor)

[1 2 3]
