# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
print(torch.rand(size=(7,7), dtype=torch.float32))

tensor([[0.9063, 0.3228, 0.3438, 0.5927, 0.0376, 0.2157, 0.1076],
        [0.3616, 0.1068, 0.5115, 0.3121, 0.6009, 0.3774, 0.7632],
        [0.4431, 0.8937, 0.8714, 0.9093, 0.3350, 0.8072, 0.2409],
        [0.8270, 0.2336, 0.8803, 0.2643, 0.5011, 0.4742, 0.4404],
        [0.0853, 0.6433, 0.7738, 0.8595, 0.5371, 0.7658, 0.6544],
        [0.7989, 0.0998, 0.8089, 0.8819, 0.8888, 0.6062, 0.8857],
        [0.4631, 0.9139, 0.2130, 0.4003, 0.5962, 0.8157, 0.1192]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [17]:
# Create another random tensor
import torch 

tensor = torch.rand(1,7)
# Perform matrix multiplication 
print(torch.matmul(tensor, tensor.T))
print(torch.matmul(tensor, torch.transpose(tensor, 0, 1)))
print(tensor @ torch.transpose(tensor, 0, 1))

tensor([[1.2619]])
tensor([[1.2619]])
tensor([[1.2619]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [18]:
# Set manual seed
import torch

# Create two random tensors
torch.manual_seed(0)
print(torch.rand(7,1))

# Matrix multiply tensors
torch.manual_seed(0)
tensor = torch.rand(1,7)
print(tensor @ tensor.T)


tensor([[0.4963],
        [0.7682],
        [0.0885],
        [0.1320],
        [0.3074],
        [0.6341],
        [0.4901]])
tensor([[1.5985]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [21]:
# Set random seed on the GPU
torch.cuda.manual_seed(0)
print(torch.rand(size=(7,1), device="cuda"))

tensor([[0.3990],
        [0.5167],
        [0.0249],
        [0.9401],
        [0.9459],
        [0.7967],
        [0.4150]], device='cuda:0')



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [23]:
# Set random seed

import torch
torch.manual_seed(1234)
# Check for access to GPU
print(torch.cuda.is_available())
print(torch.cuda.device_count())

# Create two random tensors on GPU
tensor = torch.rand(size=(2, 3))
print(tensor.to("cuda"))

True
1
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [24]:
# Perform matmul on tensor_A and tensor_B
tensor = torch.rand(size=(2, 3), device="cuda")
print(tensor @ tensor.T)

tensor([[0.9792, 0.8358],
        [0.8358, 1.4578]], device='cuda:0')


### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
print(tensor.max())

# Find min
print(tensor.min())


tensor(0.9737, device='cuda:0')
tensor(5, device='cuda:0')
tensor(0.1272, device='cuda:0')
tensor(0, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [27]:
# Find arg max
print(tensor.argmax())

# Find arg min
print(tensor.argmin())

tensor(5, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [1]:
# Set seed
import torch

torch.manual_seed(10)

# Create random tensor
random_tensor = torch.rand(1,1,1,10)
print(random_tensor)

# Remove single dimensions
squeeze_tensor = random_tensor.squeeze()
print(squeeze_tensor)

# Print out tensors and their shapes


tensor([[[[0.4581, 0.4829, 0.3125, 0.6150, 0.2139, 0.4118, 0.6938, 0.9693,
           0.6178, 0.3304]]]])
tensor([0.4581, 0.4829, 0.3125, 0.6150, 0.2139, 0.4118, 0.6938, 0.9693, 0.6178,
        0.3304])
